### PR TITLE
Js documentation and Minor changes

### PR DESCRIPTION
**Pull request by AnimeshDeb**
### jsDoc Implementation and Minor Changes
- Here are the minor updates:
  - Removed unused imports from `app.ts`
  - jsDoc implementation has been added to:
    - `getQuestion.ts`
    - `submitAnswer.ts`
    - `prismaServer.js`
  - Regarding the schema for `questionInfoTable`, the `userAnswer` field has been removed.

### CODE REVIEW

**Review by Imtiaz5 — APPROVED** [review]

**Review by DeveloperMindset123 — APPROVED** [review]
Very Thorough Explanation.

**Review by JNikolo — APPROVED** [review]
Very detailed description. I like the implementation of jsDocs to help understand everyone the functionality. I approve these changes

**Comment by DeveloperMindset123** [comment]
FIx:Merge conflicts fixed manually

**Review by wong-ja — COMMENTED** [review]
I'm getting import errors in `index.tsx` and `_layout.tsx` due to missing modules. It seems the `components` folder is missing from the repo.

**Comment by JNikolo** [comment]
Oh yeah, sadly we noticed it very late. I created a PR to fix this problem collaboratively.

**Pull request merged**
