### PR TITLE
Landing screen page

### PR DESCRIPTION
**Pull request by DeveloperMindset123**
Features Added:
- Logic for building for both android and ios
- ios : yarn ios --> should automatically build, will take a while, file configurations has been added one eas.json
- adnroid : yarn android --> same thing, should automatically build, and then can run in expo developmental build
- WIP : Logic for tabs logic still being added

### CODE REVIEW

**Comment by AnimeshDeb** [comment]
Looks good.

**Comment by JNikolo** [comment]
Looks good to merge

**Comment by Imtiaz5** [comment]
this is great! i approve of the merge.

**Review by Imtiaz5 — APPROVED** [review]

**Comment by DeveloperMindset123** [comment]
Some new changes:
1. I fixed the routing logic that wasn't working initially, tamagui's tab and screen is somewhat different that regular expo react-native and expo react-native is somewhat different than react-native navigation, personally I prefer react-native navigation over any of the formers because they overcomplicates things

2. I also implemented configurations to make sure tailwindcss is working as intended, expo only, because expo react-native's tailwindcss configuration will be different from next.js's tailwindcss config, as per the docs, there's no "one size fits all" approach that's available for tailwindcss when it comes to these two different frameworks

3. As I have mentioned earlier, I initially broke the codebase on the frontend side because they weren't working as intended as I initially hoped, but I have fixed it and made some added improvements [the first 2 points are the adjustments in the context of this paragraph]

**Comment by Imtiaz5** [comment]
pretty good

**Review by Imtiaz5 — APPROVED** [review]

**Comment by JNikolo** [comment]
The code looks nice. I just had a bug while testing the changes. 
image
I noticed the error came from the `_layout.tsx` file in `/apps/expo/app` directory, specifically in line 9:
```import '/Users/ayandas/Desktop/VS_Code_Projects/Alge-Blitz/algeblitz/apps/expo/global.css'```

By changing to:
```import '../global.css'```
the code will compile successfully. 
Looks good so far!

Notes: I tested the code in an Android development build through expo go.

**Comment by DeveloperMindset123** [comment]
> The code looks nice. I just had a bug while testing the changes. image I noticed the error came from the `_layout.tsx` file in `/apps/expo/app` directory, specifically in line 9: `import '/Users/ayandas/Desktop/VS_Code_Projects/Alge-Blitz/algeblitz/apps/expo/global.css'`
> 
> By changing to: `import '../global.css'` the code will compile successfully. Looks good so far!
> 
> Notes: I tested the code in an Android development build through expo go.

Try to use the expo developmental build, since expo go can run into unforseen errors or not render everything as intended, meaning it might not look the same when in production on the physical phone.

**Review by JNikolo — APPROVED** [review]
Works perfect!

**Review by Imtiaz5 — APPROVED** [review]

**Comment by Imtiaz5** [comment]
approved

**Review by AnimeshDeb — APPROVED** [review]
Looks good to go.

**Review by Chromium99 — APPROVED** [review]
Looking great guys!

**Review by Imtiaz5 — APPROVED** [review]

**Review by wong-ja — COMMENTED** [review]
no problems here👍

**Pull request merged**
