### PR TITLE
Create server_ci.yml for Server Continuous Integration

### PR DESCRIPTION
**Pull request by JNikolo**
This pull request introduces a new GitHub Actions workflow for continuous integration (CI) of the Algeblitz server. The most important changes include setting up the workflow to trigger on specific branches and paths, defining environment variables, and configuring the job steps for building and testing the server.

### CODE REVIEW

**Comment by JNikolo** [comment]
Added a workflow named "EAS Build" to handle the build process for the client codebase using Expo and EAS. It triggers on pushes and pull requests to the `main` branch and includes steps for checking out the code, setting up Node.js, installing dependencies, and running the build.

**Review by DeveloperMindset123 — APPROVED** [review]
Based on the file content, it looks like it only checks within backend side, can this be extended toward the frontend side? I can modify it if needed, just curious.

**Comment by JNikolo** [comment]
> Based on the file content, it looks like it only checks within backend side, can this be extended toward the frontend side? I can modify it if needed, just curious.

Yes! Please check [`client_ci.yml`](https://github.com/Chromium99/AlgeBlitz/pull/8/files#diff-66f5a2a03b03cce0bef8216ae1310224b4c5e3a6f50d44cbfb812c12f6dd4060) and let me know any changes I can do

**Comment by DeveloperMindset123** [comment]
Looks Good now, thanks a lot, this can be closed now.

**Pull request merged**
