### PR TITLE
Set up basic project structure for backend

### PR DESCRIPTION
**Pull request by JNikolo**
This pull request introduces the initial setup for the backend of the AlgeBlitz project. The changes include adding essential configuration files, setting up the Express server, and configuring TypeScript. Below is a summary of the most important changes:

### Configuration Files:

* Added `.gitignore` to exclude `node_modules` and `dist` directories. (`backend/.gitignore`)
* Created `package.json` with scripts for building, starting, and running the development server, along with dependencies and devDependencies. (`backend/package.json`)
* Added `tsconfig.json` for TypeScript configuration, specifying compiler options and strict type-checking. (`backend/tsconfig.json`)
* Created `nodemon.json` to configure Nodemon for watching TypeScript, JavaScript, and JSON files. (`backend/nodemon.json`)

### Server Setup:

* Implemented a basic Express server with CORS support and a single endpoint that returns "Hello World!". (`backend/src/app.ts`)

### Documentation:

* Added a README for the backend, detailing the structure, getting started steps, configuration files, and API endpoints. (`backend/README.md`)

### CODE REVIEW

**Review by AnimeshDeb — COMMENTED** [review]
The setup looks good to me.

**Comment by DeveloperMindset123** [comment]
Looks good, but instead of nodemon, there's a faster alternative now if you would like to use, exclusively for typescript if you would like to take a look at it. It's tsx.

Reference Link : https://stackoverflow.com/questions/37979489/how-to-watch-and-reload-ts-node-when-typescript-files-change

Also, please install this VSCode extension and configure it to be executed on save, should be automatic but you can always call on it in the search bar as well. I have added a screenshot for what it looks like.
image

**Review by DeveloperMindset123 — APPROVED** [review]
Please take a look at my comment I included in the PR

**Comment by JNikolo** [comment]
> Looks good, but instead of nodemon, there's a faster alternative now if you would like to use, exclusively for typescript if you would like to take a look at it. It's tsx.
> 
> Reference Link : https://stackoverflow.com/questions/37979489/how-to-watch-and-reload-ts-node-when-typescript-files-change
> 
> Also, please install this VSCode extension and configure it to be executed on save, should be automatic but you can always call on it in the search bar as well. I have added a screenshot for what it looks like. image

I didn't know about `tsx` at all! I'm glad you mentioned. I just tried it and it's definetely faster. I will make a quick change to use it instead of nodemon.

**Review by Imtiaz5 — APPROVED** [review]

**Pull request merged**
