### PR TITLE
setup, install, configure testing frameworks: Jest & Vitest

### PR DESCRIPTION
**Pull request by wong-ja**
### Created/Modified Files:
- `package.json` : updated to include testing scripts, dependencies, resolutions for Jest and Vitest
- `jest.config.js` : configures Jest for running tests in the project
- - sets `jest-expo` preset for React Native compatibility
- - specifies test match patterns to only include tests from the `__tests__/jest_tests` folder
- - configures coverage reporting
- `babel.config.js` : configures Babel for transpiling JavaScript/TypeScript code
- - sets `babel-preset-expo` preset for React Native support
- - includes plugins for module resolution and React Native Reanimated
- `jest.setup.js` : contains setup code for testing environment that runs before each test suite
- test files in `__tests__/jest_tests/` : for Jest test files covering various components and functionalities
- - `fileMock.js` : is used to mock static asset imports (like images) in Jest tests for example test files
- coverage reports in `coverage/` : reports generated by Jest showing which parts of the codebase are tested
- - note: this folder (build artifacts) is ignored in version control (see `.gitignore`).
- - open the `index.html` file in the `coverage/lcov-report/` to view the coverage report in HTML 
- test files in `__tests__/vitest_tests/` : for Vitest test files covering various components and functionalities
- - note: the initial Vitest setup was already present in the starter monorepo, which included basic configurations
- `vitest.config.mts` : configures Vitest for running tests in the project
- - changed to specify test match patterns to only include tests from the `__tests__/vitest_tests` folder
- 

### Running Tests:
``` 
cd algeblitz 
```
To run Jest tests, use:
```
yarn test:jest
```
To run Vitest tests, use:
```
yarn test:vitest
```
### Next Steps
As of now, no test files have been created to test the application's functionality or components. 
- Create components and functionalities. 
- Identify key components and functionalities that require testing. 
- Create tests for them.

### CODE REVIEW

**Comment by wong-ja** [comment]
fixed linter issues (Lint Code Base) by running `npx standard --fix` for javascript standard style

**Review by AnimeshDeb — APPROVED** [review]

**Review by JNikolo — APPROVED** [review]
Looks good!

**Review by AnimeshDeb — APPROVED** [review]
The changes look good overall. The addition of Jest and Vitest test configurations, along with the basic test cases, provides a solid foundation for our testing setup. The updated Babel and Jest configurations align well with the project’s requirements, and enabling code coverage is a great move for maintaining quality. I approve this PR for merging. Great work on implementing the necessary updates!

**Review by Chromium99 — APPROVED** [review]
Everything checks out and I agree with Animesh. Accommodating test cases will be great for the team going forward as we approach the end of MVP. Thank you guys for all of the hard work!

**Pull request merged**
